#!/bin/sh
#
# sharp_drm        Loads sharp_drm driver.
#

umask 077

start() {
	/sbin/modprobe sharp
	echo "OK"
}
stop() {
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
